apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-prd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: blue-prd
  sources:
  - repoURL: https://github.com/mojtabaimani/sodeko-blue-services.git
    path: blue-services/secrets/prd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: blue-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
